### ISSUE TITLE
Exclude support

### ISSUE THREAD

**Issue by thurisaz** [yamkazu/grails-database-migration#2]
Thanks for porting this to Grails 3!  It's been working just fine for us.  I notice that table exclusions haven't made it yet, i.e.

```
grails:
    profile: web
    codegen:
        defaultPackage: test-db
    plugin:
        databasemigration:
            ignoredObjects:
                -my_excluded_table
```

is not honored yet when running "grails dbm-gorm-diff."  The plugin used to do this like so:

https://github.com/grails-plugins/grails-database-migration/blob/79a2227c99336d11056a11fec97bd4100331f888/src/groovy/grails/plugin/databasemigration/MigrationUtils.groovy#L293

It looks like I could pass a DiffOutputControl to doDiffToChangeLog in https://github.com/yamkazu/database-migration/blob/master/grails-app/commands/org/grails/plugins/databasemigration/command/DbmGormDiffCommand.groovy and that _should_ exclude tables from the diff.  Are you open to PRs for this feature?

Thanks.
